[build]
  command = "bun run build"
  publish = "dist"

[dev]
  command = "bun run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = []

# Netlify configuration
[build]
  publish = "dist"
  command = "bun run build"
